### PR TITLE
add LayerDepth to Particles

### PR DESCRIPTION
**Pull request by toddgibson**
This work is in regards to Issue #381

### CODE REVIEW

**Comment by craftworkgames** [comment]
I've just had a quick glance over this on my phone. It looks good so far but I think there's a small change to make.

All public methods should default the layerDepth to zero. This way it's a non breaking change.

**Comment by toddgibson** [comment]
It should already be non-breaking since I added overloaded methods.  This way if you don't specify layerDepth it will work as normal (by using the existing methods).  But I can still make the change if you want.

**Comment by craftworkgames** [comment]
Yeah, I think it's worth doing just to reduce the code duplication.  

I believe you can just add another commit to this PR to make the changes. If you don't get around to it by tonight I don't mind just fixing it up myself. Maybe I'll try github's online editor.

**Comment by craftworkgames** [comment]
Great thanks :)

**Pull request merged**
