### PR TITLE
Add range<T>

### PR DESCRIPTION
**Pull request by ExCellRaD**
This adds `Range<T>` to the core library #174. The random values are left out because those are still in the Tweening branch.

### CODE REVIEW

**Comment by craftworkgames** [comment]
Yep. This looks pretty good.

Just one thought... The INTERPOLATOR stuff should *not* be on this class. I know it's currently commented out but I don't think it ever belongs on this class. 

@guFalcon Do you have any other comments?

**Comment by craftworkgames** [comment]
Oh, and this class is a perfect candidate for some unit tests.

**Comment by ExCellRaD** [comment]
No random value method then? I thought it would be something nice to have in the struct itself, but I can see it working the other way around too, where you would use the interpolator only where you want random values. 

>Oh, and this class is a perfect candidate for some unit tests.

I'll get on that

**Comment by craftworkgames** [comment]
> No random value method then? I thought it would be something nice to have in the struct itself, but I can see it working the other way around too

Yeah, it creates a dependency problem. We don't want low level data types depending on things like the `InterpolatorStore` or `FastRand`. Doing it like that tends to lead to a very coupled mess of code that becomes difficult to untangle later.

Think about how it works in the .NET framework. You'd never expect the `int` or `float` types to use the `Random` class internally. On the other hand it's reasonable to think that you can generate random `int`'s or `float`'s by *using* `Random`.

**Comment by ExCellRaD** [comment]
> On the other hand it's reasonable to think that you can generate random int's or float's by using Random.

We could add `T FastRand.NextFromRange<T>(Range<T>)` then? or would an extension method be more appropriate so that you could still call `T Range<T>.RandomValue()` ?

**Comment by craftworkgames** [comment]
> We could add T FastRand.NextFromRange<T>(Range<T>) then?

Something like this would be my gut feeling. There's probably more discussion to be had around the `FastRand` class. Obviously it originated in the particles feature so it might need some more thought when pulling it up into the root namespace.

This PR looks complete enough. I'll merge it soon. Thanks.

**Comment by guFalcon** [comment]
Took a quick look at it and it looks awesome. Nice work ExCellRaD.

One thing though:
Why would you have 2 properties `isDegenerate` and `isProper` where `isProper == !isDegenerate` ?

As on the random-topic I'm with Dylan.

And uuh uuh...
Maybe that's covered somewhere in MG.Ex already but when doing your randomizer, look that you can easily replace the function with some Perlin/Simplex noise. Paid off for some multiplayer-implementations (deterministic lock step) where you'd have to know what values the other players are rolling. Been there ;) But my implementation is clunky.

**Comment by ExCellRaD** [comment]
>Why would you have 2 properties isDegenerate and isProper where isProper == !isDegenerate ?

Why keep one if you can have both? :) They came from the particle Range classes, I just thought I'd keep them.

**Comment by guFalcon** [comment]
*gggg*
np. just asking.

**Comment by craftworkgames** [comment]
Merged. Thanks @ExCellRaD.

**Pull request merged**
