### PR TITLE
Fixed nuspec definitions

### PR DESCRIPTION
**Pull request by claudiuslollarius**
Modified nuspec definitions to conform to [nuspec convention to target multiple platforms](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) as described in issue #383

### CODE REVIEW

**Comment by LithiumToast** [comment]
@claudiuslollarius Shouldn't the target be `portable-net45+win8+wpa81` instead of `portable45-net45+win8+wpa81`?

**Comment by claudiuslollarius** [comment]
Not so sure: look inside:
```MonoGame.Extended\Source\MonoGame.Extended\packages.config
and you'll see even Newtonsoft JSON and MonoGame itself use
```portable45-net45+win8+wpa81
as platform moniker

**Comment by LithiumToast** [comment]
Hmm. https://docs.microsoft.com/en-us/nuget/schema/target-frameworks says otherwise.

**Comment by claudiuslollarius** [comment]
@LithiumToast Ok, updated the monikers to conform to the document you linked.

**Comment by craftworkgames** [comment]
Great work. My only concern is that we inadvertently break another platform. I mean, it should work but you don't really know until it's tested.

I can test Android but I don't have an iOS or Linux rig setup.

**Comment by craftworkgames** [comment]
Okay, after doing a little reading I'm pretty convinced this will be fine. 

I'll merge now and mention it on the gitter channel. If we have anyone complain we'll deal with that then.

**Comment by claudiuslollarius** [comment]
@craftworkgames I see you merged the pull request.

Could you please rebuild and publish updated NuGet packages? I would really need to use your library in my project.

Thank you in advance

**Comment by craftworkgames** [comment]
@claudiuslollarius Do you have a problem using the [pre-release packages](https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-use-the-pre-release-NuGet-packages)?

I wasn't planning on doing an official NuGet release for quite some time yet.

**Pull request merged**
