### PR TITLE
Gui System fixes

### PR DESCRIPTION
**Pull request by vividos**
This PR starts fixing the Gui system (see #552). I hope the fixes go into the proper direction. I reintroduced the Dialog and Image classes so that loading the skin file can find the C# classes. The GUI demo feature now starts, but doesn't properly show the three buttons, and I don't know yet why.
Comments welcome!

### CODE REVIEW

**Comment by craftworkgames** [comment]
Hey @vividos 

I really like the direction you're going with this.

Would you be willing to spend some time to create a better GUI demo that shows off more of the controls? 

Having a good demo can really help to flesh out what parts of the GUI system are working and those that need improvement.

I'll merge these changes in shortly.

**Comment by craftworkgames** [comment]
> Are you ok with adding comments to the classes so it's better documented with what they do

Sure.

**Comment by craftworkgames** [comment]
> The GUI demo feature now starts, but doesn't properly show the three buttons, and I don't know yet why.

Did you get anywhere with this?

**Comment by vividos** [comment]
Not yet. I don't know why the buttons are not correctly drawn. I'll work on a screen with all controls next. You can merge the PR of you want, I'll open a new one then.

**Comment by vividos** [comment]
I just reduced the PR to the changes I made in the deserializer and the Gui project. Please review the changes and merge them. Due to time constraints, I can't work on the Gui system in the foreseeable time. I hope the changes help you or someone other to fix the Gui system for a 2.0 release.

**Comment by craftworkgames** [comment]
Thanks mate. I'll be getting back to this sometime after I've finished what I'm currently working on but for now I'm just going to leave this PR open if that's okay with you.

**Comment by vividos** [comment]
No problem!

**Comment by vividos** [comment]
I just rebased my changes on the latest develop branch, in case you find the time to review the changes.

**Comment by craftworkgames** [comment]
This PR has been open far too long. I'll merge it today.

Can you just confirm that the demos are working?

**Comment by vividos** [comment]
I didn't compile and test the demo, just rebased the PR. Compiling worked, at least the PR days so. My changes were only the beginning of refactoring the GUI system, do I don't expect the GUI demo to be working. You can review the changes, they basically are improvements to the GUI serialization code.

**Comment by vividos** [comment]
The Gui demo works for me. My changes were more in the serializing part, which I think the Gui demo doesn't execute.

**Comment by craftworkgames** [comment]
> The Gui demo works for me. 

Okay, well in that case I'll merge it now. I'm not really focused on the GUI system this week but I think your changes are a step in the right direction.

Thanks mate.

**Comment by vividos** [comment]
You're welcome!

**Pull request merged**
