### PR TITLE
Added support for Tiled animated tiles

### PR DESCRIPTION
**Pull request by CJRii**
This will allow the running of animations from Tile Layers. The SpriteBatch extension methods have been modified to now accept an optional parameter of a GameTime instance. If one is not provided, the animations will only show the first tile of the animation. The core of the change is that now all TiledTile objects will potentially have a reference to a TiledTileSetTile which contains all the information about the animation. This also has the side-effect of being able to access the Additional Properties of the tileset tiles.
Things that will need to be updated in the future:

- When the support to display Object Layers is implemented, animations will have to implemented there as well
- When layers are refactored to be more memory friendly as discussed in issue #136 the animation code will more than likely need updating as well.

The TiledMaps Demo has been updated to utilize the new functionality.

### CODE REVIEW

**Comment by craftworkgames** [comment]
I did a quick code review and it looks good.

Did you update the demo to include animated tiles?

I'll take a closer look later.

**Comment by CJRii** [comment]
I did update the TiledMaps demo application. I should also note, this is a breaking change in that the Tiled assets from older apps will have to run through the pipeline tool again to insert the new fields the reader is expecting.

**Comment by LithiumToast** [comment]
@CJRii I think this line

```
_uniqueTileSetTiles = _animatedTiles.Select(t => t.TileSetTile).Distinct().ToList();
```

is going to cause extra garbage to be generated since it's invoked every frame.

**Comment by CJRii** [comment]
@LithiumToast That line is inside the **if** block starting at line 67:

`if (_renderTarget == null)`

so it is going to only run once per layer because `_renderTarget` will be set in that same block.

**Comment by LithiumToast** [comment]
@CJRii Ah you are right. Should looked at the whole file not just the diff.

**Comment by craftworkgames** [comment]
Wonderful work mate. Merged :smile:

**Comment by wmccullough** [comment]
Is there any way to get this change as part of a nuget package? Sorry for the necro but I'm in a position where I can't build from source atm.

Sorry for the necro.

**Pull request merged**
