### PR TITLE
Added ability to create nine patch regions in a texture atlas.

### PR DESCRIPTION
**Pull request by rds1983**
Also added method that checks whether a region exists in the texture atlas.

I develop UI library for the MonoGame: https://github.com/rds1983/Myra/
Our projects share a lot of common(bitmap fonts, texture atlases, etc). Therefore I decided to move Myra on top of MonoGame.Extended. It would require some adjustments of the MonoGame.Extended. That PR is one of it. I hope it gets through.

### CODE REVIEW

**Comment by craftworkgames** [comment]
The changes seem reasonable but I am curious; What is the use case is for this? Why do to need to add nine patches to the texture atlas? How / when do you get them back out?

Interesting GUI project you've got there. I've been working on our own GUI package in MonoGame.Extended lately. It's always good to have a few choices 👍

**Comment by rds1983** [comment]
Thing is some texture atlases' formats have nine patches. Like LibGDX.
I.e. if you take a look at this file: https://github.com/rds1983/Myra/blob/master/Source/Myra/Resources/default_uiskin.atlas
It has following sprite definition:
border-dark-blue
  rotate: false
  xy: 330, 164
  size: 3, 3
  split: 1, 1, 1, 1
  orig: 3, 3
  offset: 0, 0
  index: -1

'split:' means it is nine-patch.
So if one day you would add LibGDX texture atlases import, it would need to be able to store nine patches.

**Comment by craftworkgames** [comment]
Yeah okay. I'm just wondering if we also need a similar `GetRegion` that returns a `NinePatchRegion2D` or something.

Anyway, I'll merge this now and we can keep going if other ideas come up. Good work :)

**Comment by rds1983** [comment]
Thanks. It would be quite easy to determine whether the returned TextureRegion2D is nine patch using `is` operator.
Though I think it would be cool idea to add virtual method Draw in TextureRegion2D class and override it in NinePatchRegion2D.
So end user can do following:
```c#
var region = textureAtlas.GetRegion("myRegion");
region.Draw(...)
```
And wouldn't need to care whether the retrieved region is nine patch.

**Comment by craftworkgames** [comment]
> Thanks. It would be quite easy to determine whether the returned TextureRegion2D is nine patch using is operator.

Yep. That's true.

Just to see how it might work I just added an overload to `GetRegion` that allows the type of the region returned to be specified. It's backwards compatible with the old way but provides a little more syntax sugar if you know your region types.

            var atlas = new TextureAtlas("atlas", texture);
            atlas.CreateRegion("normal", 100, 100, 100, 100);
            atlas.CreateNinePatchRegion("nine", 0, 0, 100, 100, new Thickness(1));

            var ninePatch = atlas.GetRegion<NinePatchRegion2D>("nine");
            var textureRegion = atlas.GetRegion("normal");

> Though I think it would be cool idea to add virtual method Draw in TextureRegion2D class and override it in NinePatchRegion2D.

Actually we have something like that already in the [`TextureAtlasExtensions`](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/TextureAtlases/TextureAtlasExtensions.cs).

        public static void Draw(this SpriteBatch spriteBatch, TextureRegion2D textureRegion, Rectangle destinationRectangle, Color color, Rectangle? clippingRectangle = null)
        {
            var ninePatchRegion = textureRegion as NinePatchRegion2D;

            if (ninePatchRegion != null)
                Draw(spriteBatch, ninePatchRegion, destinationRectangle, color, clippingRectangle);
            else
                Draw(spriteBatch, textureRegion.Texture, textureRegion.Bounds, destinationRectangle, color, clippingRectangle);
        }

This method handles the situation when you've got a `NinePatchRegion2D` stored as a `TextureRegion2D`. I use this extensively in the GUI package and it works really well.

> region.Draw(...)

We've had problems coupling rendering code to the model code so having `Draw` methods on texture regions is something we want to avoid.

**Comment by rds1983** [comment]
I see. Well, according to [this](http://stackoverflow.com/questions/686412/c-sharp-is-operator-performance) using `as` has almost same performance as using enum for checking type.

I've another question. I've noticed that your implementation of BitmapFont lacks kernings. I would want to fix it. Would you accept such PR?

**Comment by craftworkgames** [comment]
> I've another question. I've noticed that your implementation of BitmapFont lacks kernings. I would want to fix it. Would you accept such PR?

Sure I guess. `BitmapFont` currently renders fonts *exactly* the same as `SpriteFont` (at least for the fonts I've tested) so just be careful to keep that in mind. I'm not sure if any of our current fonts have kerning data in the `.fnt` file. I'm curious if it would change the way they currently look?

If you're going to make any significant changes like this though, I'd like to keep the demos up-to-date with each new feature we add. So the bitmap font demo should show off kerning somehow.

I'm currently in the middle of refactoring the demos quite a bit but I'm sure we can co-ordinate our efforts.

**Comment by rds1983** [comment]
>  I'm not sure if any of our current fonts have kerning data in the .fnt file. I'm curious if it would change the way they currently look?
This one does have kernings: https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Demo.Features/Content/Fonts/impact-32.fnt
So some fonts look would definitely change their appearance.

How about temporarly adding a boolean field UseKernings(initially set to false) to the BitmapFont? Then eventually that field will be removed and kerning will be rendered.

While there, I'd suggest to review [this](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/BitmapFonts/BitmapFontExtensions.cs)
As it seems to me that every DrawString call does allocations(GetGlyphs). Probably the only way to fix it is to copy/paste GetGlyphs code to DrawString. But I think that worth it.

**Comment by LithiumToast** [comment]
@rds1983 See #365

**Comment by rds1983** [comment]
@LithiumToast good to know, thanks.

**Comment by RUSshy** [comment]
@rds1983 I like your lib because you load raw assets, if you move to MonoGame.Extended i'll loose that feature :'( (for modding)

**Comment by rds1983** [comment]
@RUSshy  not really. I am gonna keep my system of asset management.
As I also have medically confirmed allergy to the MonoGame Content Pipeline. :)

Actually, considering #139, it may go other way around, and I may move my code of loading FNT files(and also of LibGDX texture atlases) in the run time to the MonoGame.Extended. Of course, if MonoGame.Extended team won't mind.

What I'll lose is FNA support. However so far I haven't heard of anyone using my lib for the FNA.

**Pull request merged**
