### PR TITLE
[WIP] First Draft of Entity-Component-System Documentation

### PR DESCRIPTION
**Pull request by Jaden-Giordano**
This the first draft, I documented it to the best of my knowledge, though I feel its still missing a lot. I will continue to make changes as my knowledge grows and as recommendations are made.

### CODE REVIEW

**Comment by craftworkgames** [comment]
Hey mate, really great work you've been doing on these docs.

I'm just sorting out our build machine and a few other things and then I'll get around to merging these pull requests.

**Comment by craftworkgames** [comment]
@Jaden-Giordano Would you like me to merge these or would you prefer to keep the PR open until you're "done"?

**Comment by Jaden-Giordano** [comment]
I'm going to be updating this soon so I would wait until I update it.

**Comment by Jaden-Giordano** [comment]
Actually go ahead and merge this I'll make a new PR when I get to updating this. Thanks!

**Comment by craftworkgames** [comment]
Done.

**Pull request merged**
