### PR TITLE
[GUI] Adding support for parent propegation, the idea of forms and textbox highlighting

### PR DESCRIPTION
**Pull request by tspayne87**
capture

The following changes were added
- 'Padding' attribute to the 'GuiStackPanel' and 'GuiTextbox'
- Selection to 'GuiTextbox'
- CustomTypes can be passed into the GuiScreen.FromFile
- MouseMoveEvent on GuiControls
- Propagation down the control tree
- 'GuiForm' and 'GuiSubmit' where the form will allow for tabbing between controls and the enter will trigger the submit button.

### CODE REVIEW

**Comment by craftworkgames** [comment]
Hmm.. I merged the other PR and this one is reporting unresolved conflicts.

Would you mind resolving these?

**Comment by tspayne87** [comment]
The conflicts should be resolved now, I hope this helps progress the GUI system.

**Comment by craftworkgames** [comment]
> The conflicts should be resolved now, I hope this helps progress the GUI system.

Seems not. The conflict I'm seeing is on line 116 of GuiControl.cs

```
<<<<<<< develop
                var textSize = font.MeasureString(CreateBoxText(Text, font, Width));
                desiredSize.Width += textSize.Width;
                desiredSize.Height += textSize.Height;
=======
                var textSize = font.MeasureString(Text);
                fontSize.Width += textSize.Width;
                fontSize.Height += textSize.Height;
>>>>>>> develop
```

I could probably resolve it myself but I'm not currently at my normal computer. I'm not sure what the `CreateBoxText` method does. I thought maybe you'd know. But if not I'll take a look tonight.

**Comment by tspayne87** [comment]
Ok I am a little confused, I had to resolve it twice for some reason.  Anyways the conflicts should be fixed now.  Sorry about that.

>  I'm not sure what the CreateBoxText method does. I thought maybe you'd know. But if not I'll take a look tonight.

This method will convert the text to a block text if a width exists on the GuiControl.  In the snapshot I gave above it took the long string and wrapped the text based on the width of the GuiControl, instead of clipping the text off at a certain point.  If a width is not defined however it will just return the string without trying to format it.

**Comment by craftworkgames** [comment]
Great 😄

**Pull request merged**
