### PR TITLE
Entity-Component-System Redesign

### PR DESCRIPTION
**Pull request by robertdhernandez**
I took a look at the upcoming Entity-Component-System (ECS) and found it to be extremely confusing to use. I went in and modified the framework to adhere more inline to the ECS design pattern. I based it largely on [this article](https://www.gamedev.net/resources/_/technical/game-programming/understanding-component-entity-systems-r3013).

It isn't complete, but it's enough of a framework to start building off of. It's still missing a lot of its events functionality, which is what really glues it all together. The old ```ParticleEmitterSystem``` is completely broken, which are their own issue (#333). And a few demos are broken because of the changes, but I have modified the EntityComponentSystem demo to demonstrate the new API. It can use some more testing, but I wanted to get the idea.

This might be a rather drastic change out of the left field, but I found the existing upcoming entity-component-system API to be very lacking and confusing. Hopefully this new system is more straight-forward than the existing one.

### CODE REVIEW

**Comment by LithiumToast** [comment]
Couple things I noticed:
- Transform data is separated into it's own component. There was a discussion about this before. Unity for example does this, but is it really necessary? Are there examples of entities which don't have a transform component? If so, then yeah this probably makes sense. If not, then why bother with the abstraction? Why not just move the transform data directly to the entity? There might be some good reasons to decouple the two but it needs some rational in that case.
- Systems no longer process components? Entities attach systems? What is going on here? The purpose of ECS is that each system does processing with a set of components for each entity. Components don't have to be stored directly with the entity, but they should be accessible from the entity in some fashion.

**Comment by LithiumToast** [comment]
Also the following are relevant:
- #100
- http://gameprogrammingpatterns.com/component.html

**Comment by craftworkgames** [comment]
Yep. I agree with @LithiumToast on this one.

I'm all for discussing and experimenting with new designs but I can't pull this into `develop` in it's current state.

The thing about Entity Component Systems is that they are more concept than implementation. There's loads of blog posts around about the design and implementation of an ECS. Most of them share the same ideas but can have wildly different implementations.

    _logoEntity.AttachComponent(spriteCollection);
    _logoEntity.AttachSystem(new SpriteBatchSystem(GraphicsDevice, _camera, spriteBatch));
    _logoEntity.AttachSystem(new RotatorSystem());

The thing that really threw me about this approach is the way systems are attached to entities? Maybe I've missed something, but I've never seen it done this way before. As far as I can tell, doing it this way would have a serious impact on memory and performance. I am curious about the thought process behind it though?

Don't get me wrong. The current ECS implementation has a lot of room for improvement but we need to consider how it fits with the rest of the library.

**Comment by robertdhernandez** [comment]
I've been doing a little more research into the entity component system model, and found this to be very inefficient. I was also building it off of my understanding of an entity component system from another game that uses it a way similar to this. I do plan on revisiting this topic.

**Comment by LithiumToast** [comment]
If you want to talk through it let me know or open an issue about it. Having a good ECS implementation would be great 😄

**Comment by KinoshitaShimizu** [comment]
Hmm, I do also implement my own ECS (a bit like Unity does), though ended up naming all the items the same (GameObject, redundantly). I wonder if I could help on this, though, I believe my paradigm is a bit different than everyone here. For example, I like easily serializable-deserializable items, so an editor can use them properly... but I've read some classes and though I can serialize them for XNA, I don't seem to be able to deserialize them like that.

Currently I thought in adopting the ECS you use, because else I have to wrap everything around (I think I'd have to do so anyways). If it is possible I'd like to help on this matter, if still requiring help.

**Pull request closed without merging**
