### PR TITLE
Adding docs about how to build a Monogame PCL

### PR DESCRIPTION
**Pull request by WardBenjamin**
Here they are! I found some time at school today to write these today; they should be detailed enough.

Completes https://github.com/craftworkgames/MonoGame.Extended/pull/26.

Referencing https://github.com/mono/MonoGame/issues/3944 for the record.

### CODE REVIEW

**Comment by craftworkgames** [comment]
Thanks mate. That looks great.

**Comment by WardBenjamin** [comment]
No problem! Feel free to post this as a blog post by the way, it was written with that in mind.

**Comment by craftworkgames** [comment]
> Feel free to post this as a blog post by the way, it was written with that in mind.

Yeah, I was thinking that. I haven't really had time to read it properly yet but once I do I'll definitely put in on the blog so it's searchable in google.

**Comment by WardBenjamin** [comment]
Note: also completes https://github.com/craftworkgames/MonoGame.Extended/issues/36. (Just so they're linked.)

**Pull request merged**
