### PR TITLE
Artemis Entity Component System

### PR DESCRIPTION
**Pull request by LithiumToast**
Kinda rough, but it's something that works.
Still need to test entity templates, but `Entity`, `Component` and `System` all seem to be working.

EDIT: See https://github.com/thelinuxlich/artemis_CSharp/

### CODE REVIEW

**Comment by LithiumToast** [comment]
Don't merge this yet.

**Comment by LithiumToast** [comment]
@craftworkgames This looks about good now.

**Comment by LithiumToast** [comment]
There is a build error on the server with the android project?
Anyways, this is pretty solid now. The ECS demo is pretty much what is over at https://github.com/thelinuxlich/starwarrior_CSharp/

Pretty neat how reflection can be used to find types and attributes to setup how systems and entity templates and components are used. Makes prototyping a game pretty fun actually. I can totally see this being useful for game jams.

**Comment by craftworkgames** [comment]
> There is a build error on the server with the android project?

Have you pulled the latest develop into your branch? I was pretty sure I fixed this issue.

I'll take a closer look at this now :) Pretty excited to see it in action.

**Comment by craftworkgames** [comment]
That's really cool. A few rough edges but already way better than what we had before.

I noticed a run-time error in the platformer demo. Can you take a look at that before I merge?

**Comment by LithiumToast** [comment]
There seems to be a problem inherited from that Artemis fork with memory allocations using `BigInteger`.

https://github.com/thelinuxlich/artemis_CSharp/issues/46

capture

**Comment by LithiumToast** [comment]
Yup. Fixed those memory allocations by modifying `BitArray`.

**Pull request merged**
