### PR TITLE
[WIP] Demo conversion to .net core

### PR DESCRIPTION
**Pull request by jonmseaman**
I started converting the demos.

 - [X] Demo.SpaceGame works as expected.
 - [ ] Demo.StarWarrior builds but doesn't currently have collision because it used Entity.Group.
 - [x] Demo.Features needs work since there is a lot of UI code that needs updated.
  - [X] NuclexGui working as expected.
- [X] Demo.Platformer ~~crashes on startup~~, but I think that happened before .net core. It's still missing a bunch of things.

### CODE REVIEW

**Comment by craftworkgames** [comment]
Awesome work mate. I'm really impressed 😮 

> Demo.StarWarrior builds but doesn't currently have collision because it used Entity.Group.

I'm currently giving the ECS a complete overhaul in the `badguys` branch. I'll update this demo with the new ECS.

> Demo.Platformer crashes on startup, but I think that happened before .net core.

Yep. Don't worry about this one, it's been broken for ages. We already have a new Platformer demo anyway. I'll take a look over this one and see if there's anything worth salvaging then we'll delete it.

> Demo.Features needs work since there is a lot of UI code that needs updated.

This one is the most important in terms of testing the framework. We actually merged a collection of demos into this single demo at one point (I'm still not certain if that was the best choice). 

The important thing is that we get each of the [individual demos](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/Demos/Demo.Features/Demos) running somehow. The actual user interface around them is not so important. When we first put this group of demos together we had it so you could just press 'tab' to load the next demo.

The GUI system has changed quite a lot and it's still missing some features. If you're struggling with this part I'm happy to step in and take a look.

Let me know when you're ready to merge?  I can help fix up whatever's left to do.

**Comment by craftworkgames** [comment]
> Let me know when you're ready to merge? I can help fix up whatever's left to do.

Actually, it just occurred to me that I might be able to commit changes directly into the PR branch. I've never tried this before so I'll have to [look into how to do it](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/).

Right now though I'm about to go out for a while. I'll try this later tonight hopefully.

**Comment by craftworkgames** [comment]
So, cool news. 

I managed to make a couple of small changes and push them to this PR.
That's so awesome because now I can collaborate on changes before they are merged back into the `develop` branch 😄

Man, I wish I knew about this sooner.

**Comment by jonmseaman** [comment]
> The important thing is that we get each of the individual demos running somehow. The actual user interface around them is not so important. When we first put this group of demos together we had it so you could just press 'tab' to load the next demo.

image
Good news, I was able to get Demo.Features working. I didn't convert all of the demos. However, I was able to just exclude the files from the project  that aren't currently working.

**Comment by jonmseaman** [comment]
Yeah, it could be merged now. There are still a couple things that could be improved though. There are still a couple demos that were not converted. I'm not sure if you want to keep or discard those.

**Comment by craftworkgames** [comment]
Merging now. There's always things we can improve.

**Pull request merged**
