### PR TITLE
upgrade to 3.5

### PR DESCRIPTION
**Pull request by LithiumToast**
Did it properly this time without re-creating `.csproj` files...

- [x] Tested on Mac OS X El Capitan
- [x] Tested on Windows 10
- [ ] Tested on Ubuntu (I'm downloading Ubuntu now and will commit to this PR if something is wrong)

- [x] Upgraded all `.csproj` files to MonoGame 3.5; all references target the install directory of MonoGame assemblies. This includes removing any NuGet packages for MonoGame.
- [x] Upgraded all `.csproj` files to .NET Framework 4.5.
- [x] Moved all Demo projects to `Demos` folder with it's own solution.

### CODE REVIEW

**Comment by craftworkgames** [comment]
Looks really good from by initial eyeball over it.

> Moved all Demo projects to Demos folder with it's own solution.

Not sure how I feel about this. What's the benefit of having a separate solution for the demos? The whole point of moving the demos into the Source folder was so that I can run the demos while I'm working on the library to test different bits.

If it's separated into a different solution I'll have to have 2 copies of visual studio open at the same time, which isn't ideal.

**Comment by LithiumToast** [comment]
> If it's separated into a different solution I'll have to have 2 copies of visual studio open at the same time, which isn't ideal.

Hmm. Right. I guess I'll move it back into one solution, but I do think it's a good idea to move the demos a separate folder.

**Comment by craftworkgames** [comment]
> but I do think it's a good idea to move the demos a separate folder.

Yep. A `Demos` folder in the `Source` folder makes sense to me.

**Comment by LithiumToast** [comment]
Ugh. I'm having difficulty with MonoGame on Ubuntu. Specifically http://community.monogame.net/t/pipeline-tool-dllnotfoundexception/6852

**Comment by craftworkgames** [comment]
> I'm having difficulty with MonoGame on Ubuntu

Okay. That's good enough for now I guess. I'll merge it tonight.

**Comment by LithiumToast** [comment]
No. I'm looking into it hold on

**Comment by LithiumToast** [comment]
Solved that issue; having an issue actually running the demo from MonoDevelop now:

```
Loaded assembly: /media/psf/Home/Desktop/MonoGame.Extended/Demos/Demo.Camera/bin/Debug/Demo.Camera.exe
Loaded assembly: /media/psf/Home/Desktop/MonoGame.Extended/Demos/Demo.Camera/bin/Debug/MonoGame.Framework.dll [External]
Loaded assembly: /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll [External]
Loaded assembly: /media/psf/Home/Desktop/MonoGame.Extended/Demos/Demo.Camera/bin/Debug/MonoGame.Extended.dll [External]
Loaded assembly: /media/psf/Home/Desktop/MonoGame.Extended/Demos/Demo.Camera/bin/Debug/OpenTK.dll [External]
Loaded assembly: /usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll [External]
Loaded assembly: /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll [External]
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x0
  Serial number of failed request:  22
  Current serial number in output stream:  22
```

If the PR works for you on Windows I guess it's alright for now. I'll try Ubuntu again later.

**Comment by LithiumToast** [comment]
I just need to move the demos folder and add the projects to the solution hold on.

**Comment by craftworkgames** [comment]
Don't panic. I won't be doing anything for at least a few hours. I'm on a train :)

**Comment by LithiumToast** [comment]
Well, for ubuntu I'm pretty sure I mucked up my installation of MonoDevelop by going on alpha channel or something. The good news is that building content with MonoGame works in Ubuntu with the demo projects and the demo projects do build with MonoDevelop. So at least that.

**Comment by LithiumToast** [comment]
I'm re-installing Ubuntu 14.04 and trying this again tomorrow.

**Comment by craftworkgames** [comment]
Okay. Do so you want me to pull it or wait?

**Comment by craftworkgames** [comment]
I had to make [some changes](https://github.com/craftworkgames/MonoGame.Extended/commit/599c1e621d2c7332a191dc8fabe94094a17e2c22) to get everything running.

It's looking pretty good now. There's definitely something weird going on with the mouse position. I'll investigate that later.

**Comment by LithiumToast** [comment]
I'm pretty sure the mouse position is the screen mouse position, not the game window mouse position. You can easily check by running one the demos which prints the mouse position like `BitmapFonts`.

**Comment by LithiumToast** [comment]
I'm giving up on Ubuntu: It's still not working for me.

**Comment by craftworkgames** [comment]
> The only thing I can think of is that maybe the MonoGame portable library needs to be updated for 3.5.

The MonoGame PCL doesn't actually do anything. It's only there to provide the *interface* to MG.Ex which shouldn't really change since it's based of the well established XNA API. When the code executes it actually uses the copy of MonoGame that's referenced in the target application. This is called the [bait and switch](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/) trick. 

I can't really take the credit for how it works. [DDReaper sorted this out](http://darkgenesis.zenithmoon.com/monogame-goes-portable/) ages ago. However, MG.Ex relies heavily on this idea. Without bait and switch MG.Ex would never have been able to be a PCL.

> I'm giving up on Ubuntu: It's still not working for me.

Yep, fair enough. I'm ready to merge this PR into `develop` if you're okay with it. It's a hassle having to re-install MonoGame just to switch branches.

**Comment by LithiumToast** [comment]
> The MonoGame PCL doesn't actually do anything. It's only there to provide the interface to MG.Ex which shouldn't really change since it's based of the well established XNA API.

Yeah I learned about that after when I built the PCL for 3.5. Mouse position is still in screen coordinates.

> I'm ready to merge this PR into develop if you're okay with it?

Sure as long as we tell people who contribute to upgrade to 3.5 through the development installer.

**Comment by craftworkgames** [comment]
@LithiumToast I just noticed unit tests aren't running on our build server due to the upgrade to NUnit 3.2.

Is there a reason we need to upgrade NUnit? It's a real pain to upgrade our build server, but I'll do it if there's a good reason.

**Comment by LithiumToast** [comment]
@craftworkgames I just upgraded all packages I could find assuming they would have bug fixes or w/e.

**Comment by craftworkgames** [comment]
I thought you might say that. No worries. I'm going to downgrade NUnit until we have a reason to upgrade it. Thanks.

**Pull request merged**
