### PR TITLE
Get Object Group by name

### PR DESCRIPTION
**Pull request by rafaelalmeidatk**

### CODE REVIEW

**Comment by craftworkgames** [comment]
Looks great. Thanks. I'm still getting used to the whole git merge PR thing when there's conflicts.

**Comment by rafaelalmeidatk** [comment]
Why there's conflicts?

**Comment by craftworkgames** [comment]
Because I've been working in the branch too. Don't worry, I need the practice.

**Comment by rafaelalmeidatk** [comment]
Oh, understand.

**Pull request merged**
