### PR TITLE
Separate out the Tiled rendering code

### PR DESCRIPTION
**Pull request by HyperionMT**
~~This isn't ready to merge yet~~ but since this is a large PR I wanted to get it out there and start getting feedback.

Highlights:

- New FullMapRenderer which consists of all the rendering related code that used to be in the Tiled* classes.
- Also ended up fixing #144 which (although not broken at the time that issue was created) was broken as part of the last Tiled Map rendering rewrite.
- TiledMaps demo
  - New level04.tmx file to test transparency and non-square maps
  - New level05.tmx file to test isometric left-up rendering
  - Pressing Tab will cycle through available maps (5th one takes a while to load because its large)
- Decided not to extract an interface from the Tiled* classes.  As I was thinking about the changes I wanted to make I realized I was turning the Tiled* classes into a sort of generic tilemap storage system which I wasn't sure was the right way to go.  I still think it would be nice for these renderers to work for any map but since we don't support any others I won't worry about it right now

ToDo:

- ~~Unit Tests, even though this code wasn't tested before I'd like to work out some way to test it~~  Wasn't able to test it all but got a few decent tests in
- ~~Tile Animations are broken again (looks like they broke sometime during the last rewrite).  If its an easy fix I'll do it as part of this PR, still need to investigate.~~  Too much for this PR.  Underlying issue is that texture vertices are built once and not updated even when the animation changes its frame.  I think we'd need a way to update the buffer without rebuilding (time consuming on larger maps) to get the animations working.
- ~~ChunkedMapRenderer, I also want to implement a renderer that will only render the chunk surrounding the camera but this might be better to handle in a separate PR.~~  Going to handle separately

Requests:

- ~~I'm not convinced the code to group tiles by their tilesets is needed/correct.  I'd appreciate it if @OptimusPi (I modified it, but I think it was originally your code) or someone else more knowledgeable could take a look at [my comment](https://github.com/HyperionMT/MonoGame.Extended/blob/98a4880f5660825fcfc4e0440c9bbd00043708a0/Source/MonoGame.Extended/Maps/Renderers/FullMapRenderer.cs#L191) and give me their opinion.  Ignoring the fact that it might mess up rendering of isometric maps, wouldn't it be useless since we're only rendering 1 tileset (texture) at a time?~~  Underlying problem is rendering all tiles for one tileset, not the reordering of tiles

### CODE REVIEW

**Comment by craftworkgames** [comment]
> Unit Tests, even though this code wasn't tested before I'd like to work out some way to test it

Yeah, adding more unit tests is a great idea (although, not all unit tests add value, but that's a topic for another time).

Something we also need in terms of testing is a few different maps that that cover all of the different features we support. A demo that can easily switch between the maps would also be great.

> Ignoring the fact that it might mess up rendering of isometric maps, wouldn't it be useless since we're only rendering 1 tileset (texture) at a time?

For example, if we had demos / tests to prove that isometric maps and multiple tilesets are working, we could just run those after the refactor to make sure we haven't broken anything.

Fantastic work though @HyperionMT

**Comment by HyperionMT** [comment]
So I think I've addressed everything I wanted to at this point and feel its ready to be merged when you're comfortable.

By the way, I'm not sure what's up with that failed test as I don't think I touched anything related to it.

> Something we also need in terms of testing is a few different maps that that cover all of the different features we support. A demo that can easily switch between the maps would also be great.

I updated the TiledMaps demo so "Tab" switches through all available maps.

> For example, if we had demos / tests to prove that isometric maps and multiple tilesets are working, we could just run those after the refactor to make sure we haven't broken anything.

How about a demo that proves its broken? ;)
isometricproblem

Basically what we have here is a new map level05.tmx that is setup as isometric and rendered left-right, bottom-top.  Due to this, the "top" tile should hide part of the tile "beneath" it.  There are 3 tilesets with 1 tile each.  Each column should display similar to the first however as you can see they don't.  The problem is not so much reordering of tiles as it is the fact that we draw all tiles for a single tileset at a time.  For orthogonal and isometric right-down this isn't an issue.  Anyway, since this issue would have existed before this PR I think its better to handle it separately.

**Comment by craftworkgames** [comment]
> By the way, I'm not sure what's up with that failed test as I don't think I touched anything related to it.

Yeah, that test was broken the other day. I believe I fixed it in the `develop` branch. 

Did you merge the latest `develop` code into your local code before committing?

**Comment by HyperionMT** [comment]
> Did you merge the latest develop code into your local code before committing?

Good call that's what it was, missing 2 changes.

Also I tested #235 and #222 while working on this change and couldn't reproduce either so I believe they're fixed.

**Comment by craftworkgames** [comment]
Awesome work. I've closed those other 2 issues.

I'll merge this now.

**Comment by HyperionMT** [comment]
Thanks @craftworkgames.  Also, I realize I didn't use the correct keywords to get #144 and #268 to close automatically (I promise I'll be better about this in the future).  Could you please close those two out when you get a chance?

**Pull request merged**
