### PR TITLE
Revert "Platform-based build configurations"

### PR DESCRIPTION
**Pull request by craftworkgames**
Reverts craftworkgames/MonoGame.Extended#29

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Hmm yeah this is odd. I'm not yet running Windows 10, but it seemed to work fine in VS 2013 Community. I'll investigate a bit if I can.

**Comment by craftworkgames** [comment]
I doubt Windows 10 is the issue. VS2015 might be though.

**Comment by WardBenjamin** [comment]
Yeah, that's what I was thinking. Sorry for the ambiguity.

**Comment by craftworkgames** [comment]
If we can't get this approach to work it might be worth considering alternatives. Another option might be to have 2 Sandbox projects (Sandbox.Windows and Sandbox.Linux) that share code between them.

**Pull request merged**
