### PR TITLE
Updated MonoGame Versions

### PR DESCRIPTION
**Pull request by Emersont1**
MG: 3.8  -> 3.8.1
dotnet:
+ coreapp3.1 -> net6
+ netstandard2.0 -> net6

### CODE REVIEW

**Comment by Emersont1** [comment]
I'm not completely sure why that stage is failing just on the ubuntu runner

**Comment by damian-666** [comment]
btw   I don't know if u did they manually but im getting decent results using the upgrade-assistant.   also im using your wpf content control and i have to move it up soon to netcore from 4.8... im trying dotnet tool install -g upgrade-assistant
then donet tool upgrade-assistant analyze XXX.sln   thx..

**Comment by Emersont1** [comment]
I didn't know the upgrade assistant existed

**Comment by OliverAThunes** [comment]
Seems like the deployment is complaining about the API key not being set. A maintainer or the lead dev has to look at that I think.

**Comment by sandord** [comment]
Shouldn't the default effect from `MonoGame.Extended.Graphics\Effects\Resources` be recompiled for MonoGame 3.8.1 using the `RebuildEffects.bat` file? Or is that done in the build pipeline?

**Comment by lithiumtoast** [comment]
API key is only available upon non PR.

**Pull request merged**
