### PR TITLE
Added Animation class

### PR DESCRIPTION
**Pull request by cra0zy**
#15

### CODE REVIEW

**Comment by cra0zy** [comment]
@craftworkgames I changed the default origin of Sprite to 0, 0 because everything in XNA has that as it's default origin.

**Comment by craftworkgames** [comment]
> I changed the default origin of Sprite to 0, 0 because XNA uses that as default origin.
It would be confusing if some classes were using 0, 0 as default, and others were centering.

Which classes specifically? I have a list of the classes [here](http://www.dylanwilson.net/list-of-xna-classes-grouped-by-dll) for reference.

Personally I still think it should default to the center because I think that's a more useful value when rotating the sprite. Rotating around the top left (or any other corner) is rarely useful. However, I'm always open to change it if there's a good reason.

I posted [the question on twitter](https://twitter.com/craftworkgames/status/642883019171172352) to see if I could get some outside opinions. I got two different opinions so far:

> Dylan Wilson ‏@craftworkgames
Opinion poll: should a Sprite class have a default Origin of top left or centre? #monogame #gamedev

> Scott Sebelius ‏@scottsebelius
@craftworkgames the obvious leaning for a sprite would be center since you think of center body as local and world position
> @scottsebelius that was my thinking too. I'm hoping to get a few more opinions on the matter.

> Patrick Weigel ‏@PatrickW462
@craftworkgames Bottom right. So we can finally correctly animate someone walking.
> @PatrickW462 wouldn't that be bottom middle?
> @craftworkgames More like wherever the foot is, so that animations can keep that point fixed. Bottom middle is a good place.
> @PatrickW462 seems kind of arbitrary but I guess so is centre and top left.
> @PatrickW462 rotation around the feet doesn't make sense though.


Changes like this can seem tiny on the surface but if they are not done carefully they can be far reaching and create frustrating bugs. I'd really prefer that we get into a habit of discussing them before making them please.

**Comment by craftworkgames** [comment]
Btw.. now some tests are failing.
http://build.craftworkgames.com/viewLog.html?buildId=379&tab=buildResultsDiv&buildTypeId=MonoGameExtended_CI

**Comment by cra0zy** [comment]
I know why the tests are failing I'll fix it a bit later today, I didn't know you've setup a teambuild server, nice.

As for what classes that use top left, spritebatch and texture2d, spritebatch and spritefont. I do understand wanting to center sprites(considering a lot of game engines do it), but for XNA you usually get used to thinking of 0, 0 as default origin for everything.

If we were building our own game engine I would go for centering, but since we are doing an extension on XNA, it makes a lot more sense to use 0, 0.

**Comment by craftworkgames** [comment]
> spritebatch and texture2d, spritebatch and spritefont.

So basically the *only* class in XNA that has anything to do with the origin is SpriteBatch. Yes, it is [documented](https://msdn.microsoft.com/en-us/library/ff433992.aspx) to have a default origin of (0, 0) but I hardly think that's a good reason to follow suit.

> I do understand wanting to center sprites(considering a lot of game engines do it),

Yes, a lot of game engines do it because it makes sense. Our goal is to make it easier to make games with MonoGame. Setting the default origin to the top left corner is rarely useful when making games and I think having the center as the default is adding value to the Sprite class. In the few cases when it does make sense to use the top left corner (e.g. rendering a tile based map) you'll probably not be using the Sprite class anyway.

> but for XNA you usually get used to thinking of 0, 0 as default origin for everything.

Even if you *think* the default origin is 0, 0 for the Sprite class the first time you use it, you'll not likely want to leave it that way. The *most* likely scenario is that you'll want to set the origin to something other than the top left corner in almost all cases. It just doesn't make any sense.

**Comment by cra0zy** [comment]
@WardBenjamin What do you think?

**Comment by WardBenjamin** [comment]
@cra0zy Personally, I'd prefer the center of the sprite for the default origin since most often (always?) that's how I've used it. I mean, yes, nothing in the MonoGame API uses it, but our goal is to make this more intuitive and useful than the MG API alone, and I think that's a part of it.

**Pull request merged**
