### PR TITLE
Resolve relative paths for tileset sources in tiled map importer

### PR DESCRIPTION
**Pull request by merthsoft**
Fixes issue #712

### CODE REVIEW

**Comment by lithiumtoast** [comment]
Thanks 😃 

Could you rebase? I pushed a small commit that should fix the check for deploying.

**Comment by merthsoft** [comment]
actually we should hold off on this. I'm getting some strange results while debugging now that I need to clear up.

**Comment by merthsoft** [comment]
Ok never mind it seems ok! I've merged dev

**Comment by lithiumtoast** [comment]
The last job in the workflow fails because forks don't have access to GitHub secrets. I need to look into this more...

Otherwise, great!

**Pull request merged**
